file(REMOVE_RECURSE "${TEST_ROOT}")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${PROVIDER_BUILD}" --prefix "${TEST_ROOT}/install"
  RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Provider install failed")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${SOURCE_DIR}" -B "${TEST_ROOT}/consumer"
  -DCMAKE_PREFIX_PATH=${TEST_ROOT}/install RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Installed package consumer configure failed")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${TEST_ROOT}/consumer" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Installed package consumer build failed")
endif()
execute_process(COMMAND "${TEST_ROOT}/consumer/consumer" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Installed package consumer run failed")
endif()
